version: "3.7"

services:
  jenkins:
    image: jenkins
    build:
      context: ./jenkins
      # args:
      #   DOCKER_GID: ${DOCKER_GID}
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`${HOST}`)"
      - "traefik.http.routers.jenkins.rule=PathPrefix(`/jenkins`)"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
    
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
      - GITHUB_PRIVATE_KEY=${GITHUB_PRIVATE_KEY}
      - GITHUB_APP_ID=${GITHUB_APP_ID}
      # - DOCKER_PATH=${DOCKER_PATH}
      - ORGANIZATIONS=${ORGANIZATIONS}
      - SSH_PRIVATE_FILE_PATH=${SSH_PRIVATE_FILE_PATH}
      - ADMIN_USERS=${ADMIN_USERS}
      - GITHUB_REPO_OWNER=${GITHUB_REPO_OWNER}
      - JENKINS_URL=${JENKINS_URL}
      # - JENKINS_VAULT_ROLE_ID=${JENKINS_VAULT_ROLE_ID}
      # - JENKINS_VAULT_SECRET_ID=${JENKINS_VAULT_SECRET_ID}
      # - MINIKUBE_KEY_PATH=${MINIKUBE_KEY_PATH}
      # - MINIKUBE_KEY_SECRET=${MINIKUBE_KEY_SECRET}
      - ECS_AGENT_CLUSTER= ${ECS_AGENT_CLUSTER}
      - AGENT_SECURITY_GROUP=${AGENT_SECURITY_GROUP}
      - SUBNETS=${SUBNETS}
    ports:
      - 8080:8080
      - 50001:50000
    container_name: jenkins
    networks:
      - jenkins-net
    # volumes:
      # Folders need to have 1000:1000 ownership or use volume
      # - ./jenkins_home:/var/jenkins_home
      # - ./jenkins_logs:/var/log/jenkins
      # - /var/run/docker.sock:/var/run/docker.sock
      # just mounting to ease development
      # - ./jenkins/config/casc_configs:/usr/share/jenkins/ref/casc_configs
  
  
  # traefik:
  #   image: "traefik:v2.5"
  #   container_name: "traefik"
  #   ports:
  #     - "80:80"
  #     - "8090:8080"
  #   volumes:
  #     - ./traefik/config/traefik.yml:/etc/traefik/traefik.yml 
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"
  #   networks:
  #     - jenkins-net




networks:
  jenkins-net:
