version: "3.7"

services:
  jenkins:
    build:
      context: ./jenkins
      args:
        DOCKER_GID: ${DOCKER_GID}
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_ADMIN_ID=${JENKINS_ADMIN_ID}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
      - GITHUB_PRIVATE_KEY=${GITHUB_PRIVATE_KEY}
      - GITHUB_APP_ID=${GITHUB_APP_ID}
      - DOCKER_URI=${DOCKER_URI}
      - SSH_PRIVATE_FILE_PATH=${SSH_PRIVATE_FILE_PATH}
      - ADMIN_USERS=${ADMIN_USERS}
      - GITHUB_REPO_OWNER=${GITHUB_REPO_OWNER}
      - JENKINS_VAULT_ROLE_ID=${JENKINS_VAULT_ROLE_ID}
      - JENKINS_VAULT_SECRET_ID=${JENKINS_VAULT_SECRET_ID}
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    networks:
      - jenkins-net
    volumes:
      # Folders need to have 1000:1000 ownership or use volume
      - ./jenkins_home:/var/jenkins_home
      - ./jenkins_logs:/var/log/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
      # just mounting to ease development
      - ./jenkins/config/casc.yaml:/usr/share/jenkins/ref/casc.yaml
    # secrets:
    #   - jcasc_vault
  
  web:
    container_name: nginx
    depends_on:
      - jenkins
      - vault
      - consul
    build:
      context: ./web
    ports:
        - "80:80"
    networks:
      - jenkins-net
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
      - JENKINS_URL=${JENKINS_URL}
      - JENKINS_PORT=${JENKINS_PORT}
      - JENKINS_PATH=${JENKINS_PATH}
      - VAULT_HOST=${VAULT_HOST}
      - VAULT_PORT=${VAULT_PORT}
      - VAULT_PATH=${VAULT_PATH}

  vault:
    container_name: vault
    image: vault:latest
    ports:
      - "8200:8200"
    depends_on:
      - consul
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      # - HOME=/var/vault
      # - VAULT_DEV_ROOT_TOKEN_ID="vault-plaintext-root-token"
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/config/vault.hcl
    # command: vault server -config=/config/vault.hcl
    volumes_from:
      - consul
    networks:
      - jenkins-net

  consul:
    container_name: consul
    image: consul:latest
    ports:
        - "8500:8500"
        - "8300:8300"
    volumes:
        - ./consul/config:/config
        - ./consul_data/data:/data
    command: agent -server  -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1 #-data-dir=/data
    networks:
      - jenkins-net
  


networks:
  jenkins-net:

# secrets:
#   jcasc_vault:
#     file: ./keys/jcasc_vault