credentials:
  system:
    domainCredentials:
    - credentials:
      ## MANDATORY
      # Need to setup Github OAuth: https://github.com/jenkinsci/github-oauth-plugin
      - string:
          description: "Github OAuth Token"
          id: "github-token"
          scope: GLOBAL
          secret: ${GITHUB_ACCESS_TOKEN}
      # Need to create a Github APP: https://github.com/jenkinsci/github-branch-source-plugin/blob/master/docs/github-app.adoc
      - gitHubApp:
            appID: ${GITHUB_APP_ID}
            description: "GitHub app"
            id: "github-app"
            # apiUri: https://my-custom-github-enterprise.com/api/v3 # optional only required for GitHub enterprise
            privateKey: "${readFile:${SSH_PRIVATE_FILE_PATH}}"
      - vaultAppRoleCredential:
          id: "vault-app-role"
          # these commited values are test values, replace with your own
          roleId: ${JENKINS_VAULT_ROLE_ID}
          secretId: ${JENKINS_VAULT_SECRET_ID}
          scope: GLOBAL